version: '3.9'
services:
  
  nginx:
    image: 'praniknikose/button-roulette-nginx:latest'
    container_name: roulette-nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
  
  backend:
    image: 'praniknikose/button-roulette-backend:latest'
    container_name: roulette-backend
    environment:
      SERVER_PORT: 8888
      FRONTEND_URL: 'http://16.171.24.117/'
    restart: unless-stopped
  
  frontend:
    image: 'praniknikose/button-roulette-frontend:latest'
    container_name: roulette-frontend
    depends_on:
      - backend
    restart: unless-stopped
